In [60]:
from datetime import datetime
from utils import *
import json
import os

file_dir = os.path.join(os.curdir, "../../Data/Embedding/Divided")

In [ ]:
# Search Date YYYYMMDD
Date = input()
print(Date)
year = Date[:4]
Q = f"Q{int(Date[4:6]) // 4 + 1}"
for file in os.listdir(file_dir):
    if Q in file and year in file:
        print(file)
        with open(os.path.join(os.curdir, "../../Data/Embedding/Divided",file), mode="r") as f:
            data = json.load(f)
        break
link_list = []
vector_arr = []

for embedding in data:
    if Date in embedding["ID"][:8]:
        link_list.append(embedding["Link"])
        vector_arr.append(embedding["embedding"])

20221208
005930_2022_processed_embedded_Q4.json


In [62]:
for link in link_list:
    print(link)

m = cos_sim_matrix(np.array(vector_arr), 3)
print(m)

https://n.news.naver.com/mnews/article/001/0013631845?sid=105
https://n.news.naver.com/mnews/article/011/0004131098?sid=101
https://n.news.naver.com/mnews/article/014/0004939687?sid=101
https://n.news.naver.com/mnews/article/015/0004785242?sid=101
https://n.news.naver.com/mnews/article/016/0002075839?sid=101
https://n.news.naver.com/mnews/article/056/0011389144?sid=101
https://n.news.naver.com/mnews/article/277/0005189159?sid=101
https://n.news.naver.com/mnews/article/277/0005189166?sid=101
https://n.news.naver.com/mnews/article/366/0000860913?sid=105
[[1.    0.456 0.658 0.495 0.478 0.331 0.351 0.564 0.361]
 [0.456 1.    0.594 0.65  0.588 0.442 0.503 0.558 0.395]
 [0.658 0.594 1.    0.588 0.53  0.402 0.44  0.557 0.403]
 [0.495 0.65  0.588 1.    0.567 0.471 0.486 0.545 0.552]
 [0.478 0.588 0.53  0.567 1.    0.421 0.458 0.526 0.385]
 [0.331 0.442 0.402 0.471 0.421 1.    0.498 0.49  0.462]
 [0.351 0.503 0.44  0.486 0.458 0.498 1.    0.529 0.366]
 [0.564 0.558 0.557 0.545 0.526 0.49  0.529

In [63]:
(m > 0.8) * 1

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]])

데이터에 대한 클러스터를 하려고 하는건데
너무 어려운 문제가 많다

주제어 골라오는 문제들
그거를 중복으로 골라내는 문제
필터링을 해보자 ~~